version: '3'
services:
  rsyslog:
    build: 
      context: ./rsyslog/
      dockerfile: Dockerfile
    ports:
      - "5140:5140/udp"
      - "5140:5140/tcp"
    volumes:
      - /sb:/sb
    restart: always
    networks:
      - syslog-net
  fluent:
    build: 
      context: ./fluent-bit/
      dockerfile: Dockerfile
    ports:
      - "515:515/tcp" # This can be removed and is not necessary for the functioning of the server
    restart: always
    networks:
      - syslog-net
networks:
  syslog-net:
    ipam:
      driver: default